# Generated by Django 4.2.7 on 2023-12-17 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='razorpyay_order_id',
            new_name='order_id',
        ),
    ]
