# Generated by Django 4.2.7 on 2023-12-01 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_amount_collectiondata_enteredamount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectiondata',
            old_name='enteredAmount',
            new_name='Amount',
        ),
    ]
